changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.3.3.cjs

packageExtensions:
  '@thematic/d3@*':
    peerDependencies:
      "@types/d3-axis": "*"
  '@fluentui/react@*':
    peerDependencies:      
      "@types/prop-types": "*"
      "prop-types": "*"
  'office-ui-fabric-react@*':
    peerDependencies:
      "@types/prop-types": "*"
      "prop-types": "*"
  '@uifabric/styling@*':
    peerDependencies:
      "@types/react": "*"
  '@thematic/fluent@*':
    peerDependencies:
      "@uifabric/icons": "*"
  '@testing-library/react@*':
    dependencies:
      'pretty-format': '26.5.2'
      '@types/pretty-format': '^24.3.0'
