name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Remotes
        run: git remote -v

      - name: Version Check
        run: yarn version check

      - run: yarn install
        name: Install Dependencies
        env:
          CI: true

      - run: yarn ci
        name: Execute Tests
        env:
          CI: true
